kubernetes model creation plugin implementation
IAC2-Project/iacmf pull request #31
Opened 2023-04-23 21:59 UTC by rohitghegde

2023-04-25 16:18 UTC, rohitghegde commented
@ghareeb-falazi  I have disabled the kubernetes model creation plugin and the build is successful now

2023-05-02 13:26 UTC, ghareeb-falazi requested changes
Please fix some minor issues with the PR

2023-05-02 13:26 UTC, ghareeb-falazi commented on src/main/java/org/iac2/service/architecturereconstruction/common/exception/NameSpaceNotFoundException.java
> +public class NameSpaceNotFoundException extends RuntimeException {
Please make this exception inherit from one of the exceptions defined in `org.iac2.common.exception`

2023-05-02 13:26 UTC, ghareeb-falazi commented on src/main/java/org/iac2/service/architecturereconstruction/common/model/Kubernetes/ContainerComponentRelations.java
> +public class ContainerComponentRelations {
Make singular, i.e., relation not relations

2023-05-02 13:26 UTC, ghareeb-falazi commented on src/main/java/org/iac2/service/architecturereconstruction/common/model/Kubernetes/ContainerComponentRelations.java
Kubernetes-specific model classes must be within the `org.iac2.service.architecturereconstruction.plugin.implementation.kubernetes.model` namespace not the `org.iac2.service.architecturereconstruction.common.model` namespace. The latter is used exclusively for technology-agnostic model entities (i.e., EDMM)

2023-05-02 13:26 UTC, ghareeb-falazi commented on src/main/java/org/iac2/service/architecturereconstruction/common/model/Kubernetes/ContainerComponentRelations.java
> +    private String containerType;
`containerType` seems to be unused. Please remove it if so.

2023-05-02 13:26 UTC, ghareeb-falazi commented on src/main/java/org/iac2/service/architecturereconstruction/common/model/Kubernetes/ContainerComponentRelations.java
> +    private String relationType;
Consider using an enum instead of constant strings

2023-05-02 13:26 UTC, ghareeb-falazi commented on src/main/java/org/iac2/service/architecturereconstruction/common/model/Kubernetes/ContainerComponentRelations.java
> +    private String containerName;
`containerName` seems to be unused. Please remove it if so.

2023-05-05 07:38 UTC, ghareeb-falazi approved these changes

2023-05-05 07:59 UTC, merged